version: "3.9"
services: 
  api: 
    container_name: menu_api
    build: .
    command: >
      sh -c "python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app